W-12067424-rns-migration-cv
mulesoft/docs-rpa pull request #101
Opened 2022-12-01 19:54 UTC by Cristian-Venticinque

Migrating Release notes to docs-rpa repo.
Restructuring to make them reusable.
Adding Builder 6.1 RNs.

2022-12-05 15:32 UTC, ahelmbold requested changes
See comments.

2022-12-05 15:32 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +* You can now capture _Mouse Over_ events using the `F2` key.
+ "while recording Web Tasks" - also this feature was added for the Web Task recording, previously it was only available for Bot Tasks.

2022-12-05 15:32 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +* You can now activate or deactivate hotkeys.
Add additional information "...hotkeys to control the RPA Recorder"

2022-12-05 15:32 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +* The new *Open log file* button enables you to open the latest log file.
Add additional information "...button in settings -> Log files" - there is a new Tab in the Settings called "Log files" where this button is found.

2022-12-05 15:32 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +* The new *Open log files directory* enables you to open the folder containing all RPA Recorder logs in your local computer.
Add additional information "...button in settings -> Log files" - there is a new Tab in the Settings called "Log files" where this button is found.

2022-12-05 15:32 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +* RPA Recorder now adds the remote debugging port to the start arguments, which enables external access to the browser wizard.
Not sure about this is really needed to display here, will check with Alexander Susdorf

2022-12-05 15:32 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +
Add another in Whats new:
Added browser specific hotkeys for Web Task recording to control web browser navigation
See [W-11246241](https://gus.lightning.force.com/a07EE00000yTFjLYAW)

2022-12-05 15:32 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +| Using special characters for process names no longer causes errors. | W-?
W-11954860

2022-12-05 15:32 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +| RPA Recorder no longer fails to login to RPA Manager when the user password contains specific special characters | W-?
W-12064751

2022-12-06 09:13 UTC, ahelmbold requested changes
Everything good, only the one item in line 25 can be removed.

2022-12-06 09:13 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.1.0-release-notes.adoc
> +// TBC - * RPA Recorder now adds the remote debugging port to the start arguments, which enables external access to the browser wizard.
Checked with Alex and this can be removed, was only an internal, not customer facing change

2022-12-06 19:30 UTC, fermujica submitted a review, later dismissed

2022-12-06 19:36 UTC, fermujica approved these changes

2022-12-06 19:37 UTC, merged