W-12588607-stopwatch-collection-cv
mulesoft/docs-rpa pull request #136
Opened 2023-03-02 19:47 UTC by Cristian-Venticinque

2023-03-07 14:43 UTC, ms-tlu requested changes
Hi Cristian,
we also updated the Wizard so the Timer / Reached / Value Label input fields are in the same order, so you might want to update the screenshot with the newest version

2023-03-07 14:43 UTC, ms-tlu commented on rpa-builder/6.2/modules/ROOT/pages/toolbox-measurement-points-stopwatch-collection.adoc
> +The Stopwatch Collection Action Step enables you to collect all timer values from the Stopwatch Action Steps configure in an Activity Workflow.
We should mention here that the Stopwatch Collection contains both Timers from the Stopwatch Action Step AND the General Timer Actions Step

2023-03-09 16:12 UTC, JennyHajee approved these changes

2023-03-09 16:12 UTC, JennyHajee commented on rpa-builder/6.2/modules/ROOT/pages/toolbox-measurement-points-stopwatch-collection.adoc
> +The label for the Stopwatch Name in the output JSON
```suggestion
The label for the Stopwatch Name in the output JSON.

```

2023-03-09 16:12 UTC, JennyHajee commented on rpa-builder/6.2/modules/ROOT/pages/toolbox-measurement-points-stopwatch-collection.adoc
> +The label for the Stopwatch Reached State in the output JSON
```suggestion
The label for the Stopwatch Reached State in the output JSON.

```

2023-03-09 16:12 UTC, JennyHajee commented on rpa-builder/6.2/modules/ROOT/pages/toolbox-measurement-points-stopwatch-collection.adoc
> +The label for the Stopwatch Value in the output JSON
```suggestion
The label for the Stopwatch Value in the output JSON.

```

2023-03-22 19:48 UTC, merged