RPA Manager Release notes 2023-03/1.
mulesoft/docs-rpa pull request #139
Opened 2023-03-08 19:24 UTC by jhammann72

2023-03-09 11:32 UTC, sebermuley requested changes

2023-03-09 13:53 UTC, jhammann72 commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-manager-release-notes.adoc
> +| An outage (crash, reboot, etc.) of the RPA Bot no longer stops the process execution after the RPA Bot is running again. | W-12361095
Here it is important to emphasize that the Bot cannot resume an aborted process execution. The issue was that the Bot never restarted the respective process again after a crash or reboot.

2023-03-09 13:58 UTC, Cristian-Venticinque commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-manager-release-notes.adoc
> +| An outage (crash, reboot, etc.) of the RPA Bot no longer stops the process execution after the RPA Bot is running again. | W-12361095
What about this? 
_RPA Manger now automatically restarts process executions carried out by an RPA Bot when the bot restarts due to a failure, like a crash or system reboot. | W-12361095_

2023-03-09 14:51 UTC, jhammann72 commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-manager-release-notes.adoc
> +| An outage (crash, reboot, etc.) of the RPA Bot no longer stops the process execution after the RPA Bot is running again. | W-12361095
Sounds good.

2023-03-13 10:34 UTC, sebermuley approved these changes

2023-03-13 16:53 UTC, merged