W-14245604-recorder 6.4.4 rns
mulesoft/docs-rpa pull request #274
Opened 2023-10-05 21:24 UTC by tasmoore

2023-10-06 07:53 UTC, Alexander-S-Salesforce requested changes

2023-10-06 07:53 UTC, Alexander-S-Salesforce commented on rpa-home/modules/ROOT/pages/_partials/release-notes/rpa-recorder-6.4.4-release-notes.adoc
> +|The CefSharp.Common library is upgraded to version 116.0.23 to address reported security vulnerabilities.| W-14234524
Sorry, there was a "0" missing in our Confluence page.
The correct version is 116.0.230 , not .160.0.23

2023-10-09 15:23 UTC, Alexander-S-Salesforce approved these changes

2023-10-09 15:24 UTC, Alexander-S-Salesforce submitted a review, later dismissed

2023-10-09 16:19 UTC, Cristian-Venticinque submitted a review, later dismissed

2023-10-10 15:10 UTC, dmerlob approved these changes

2023-10-10 15:12 UTC, merged