W-15585387 Add troubleshooting Azure guide.
mulesoft/docs-rpa pull request #384
Opened 2024-05-23 18:17 UTC by Cristian-Venticinque

2024-05-24 16:54 UTC, ms-tlu requested changes, later dismissed

2024-05-24 16:54 UTC, ms-tlu commented on rpa-builder/6.6/modules/ROOT/pages/troubleshooting-azure-oauth-setup.adoc
> +** Provide a Redirect URI.
This is a regular point of confusion for customers, I think we should emphasize that the URL needs to be any valid URL and should provide an example like http://localhost:49453/

2024-05-27 18:43 UTC, Crispy-Salesforce submitted a review, later dismissed

2024-05-27 18:43 UTC, Crispy-Salesforce commented on rpa-builder/6.6/modules/ROOT/pages/troubleshooting-azure-oauth-setup.adoc
> +After creating the secret, ensure you copy its *Value* as this is the only time you can see it. After you leave this page, the secret is not accessible anymore.
```suggestion
After creating the secret, ensure you copy its *Value* as this is the only time you can see it. After you leave this page, the secret is no longer accessible. 
```

2024-05-27 18:43 UTC, Crispy-Salesforce commented on rpa-builder/6.6/modules/ROOT/pages/troubleshooting-azure-oauth-setup.adoc
> +. Select the appropriate permissions and protocols depending on your Workflow needs:
```suggestion
. Select the appropriate permissions and protocols depending on your workflow needs: 
```

2024-05-27 18:43 UTC, Crispy-Salesforce commented on rpa-builder/6.6/modules/ROOT/pages/troubleshooting-azure-oauth-setup.adoc
> +. Select the appropriate permissions and protocols depending on your Workflow needs:
If "Workflow" is the name of a feature, dismiss this suggestion.

2024-05-27 18:43 UTC, Crispy-Salesforce commented on rpa-builder/6.6/modules/ROOT/pages/troubleshooting-azure-oauth-setup.adoc
> +If you are not sure which of these apply to your case, select all of them.
```suggestion
If you don't know the permissions and protocols that apply to your case, select all of them. 
```

2024-05-27 18:49 UTC, Crispy-Salesforce approved these changes

2024-05-27 18:50 UTC, merged