W-16153452 gmail with oauth update
mulesoft/docs-rpa pull request #408
Opened 2024-08-16 18:23 UTC by Cristian-Venticinque

2024-08-20 12:51 UTC, Cristian-Venticinque commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +* *OAuth Host Address*
```suggestion
* *Auth Endpoint* 
* *Token Endpoint* 
```

2024-08-21 16:32 UTC, Cristian-Venticinque commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +**  *Encryption used*
```suggestion
** *Encryption used*
```

2024-08-22 14:07 UTC, ahelmbold commented on rpa-builder/6.7/modules/ROOT/pages/_partials/generate-oauth-token-steps.adoc
> +. Paste the token in an alphanumeric Server Based Variable.
Rename 'Server Based Variable' to 'Activity Parameter'.

Server Based Variable is a very old term from Servicetrace, no longer valid in MS RPA.

2024-08-22 14:08 UTC, ahelmbold commented on rpa-builder/6.7/modules/ROOT/pages/_partials/generate-oauth-token-steps.adoc
> +By using a Server Based Variable you don't need to upload a new version of your Workflow to RPA Manager if your token expires or your user gets logged out of your email provider. In this case, regene
Rename 'Server Based Variable' to 'Activity Parameter'.

2024-08-22 14:36 UTC, ahelmbold commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +You must have an Azure account to create an application for Outlook.
Enhance this for both MS Outlook and Gmail, for both users must create an application

2024-08-22 14:38 UTC, ahelmbold commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +To enable using different accounts to log in, Mail Session (Outlook with OAuth) clears credentials stored in browser cookies when you click *Authenticate*.
Rename 'Mail Session (Outlook with OAuth)' to 'Mail Session (OAuth)'

2024-08-22 14:38 UTC, ahelmbold commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +Instead of authenticating via the *Mail Session (Outlook with OAuth) wizard*, you can pin the refresh token if you obtain it externally. In this case, you still need to populate or pin the remaining
Rename 'Mail Session (Outlook with OAuth)' to 'Mail Session (OAuth)'

2024-08-22 14:38 UTC, ahelmbold requested changes
See comments

2024-08-23 17:27 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +* An Azure account, if you are creating an application for Outlook.
```suggestion
* An Azure account, if you are creating an application for Outlook
```

2024-08-23 17:27 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +* A Google account, if you are creating an application for Gmail.
```suggestion
* A Google account, if you are creating an application for Gmail
```

2024-08-23 17:28 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +(Mail Protocol) The communication protocol to use: IMAP, Exchange, or POP3.
(No terminating punctuation for (all) these sentence-fragment bullets.)

2024-08-23 17:29 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +(Mail Protocol) The communication protocol to use: IMAP, Exchange, or POP3.
Would a table be better?

2024-08-23 17:30 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +(String) The Email address to which the test email is to
```suggestion
(String) The email address to which the test email is to
```

2024-08-23 17:31 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +* *E-Mail Address*
Suggest to UX to make this "Email"?

2024-08-23 17:32 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +image:mail-session-outlook-oauth-wizard.png[The Mail Session (OAuth) Action Step Wizard, 60%, 60%]
best practice: alt text in quotes. Also, I think we don't use resize parameters?

2024-08-23 17:32 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +image:mail-session-outlook-oauth-wizard.png[The Mail Session (OAuth) Action Step Wizard, 60%, 60%]
Should Wizard be lowercase here?

2024-08-23 17:33 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +In *Operation Mode* you determine what happens and which area activates in the Mail Session. The
```suggestion
In *Operation Mode*, you determine what happens and which area activates in the Mail Session. The
```

2024-08-23 17:33 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +Enables you to configure the Incoming and Outgoing
Should these UI options be bold?

2024-08-23 17:34 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +If you select the _Read mails from inbox_ mode, you can't use the Send Mail Action Step.
bold rather than italic?

2024-08-23 17:37 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +The *OAuth Authentication* section enables you to create a set of tokens that don't rely on a user password to authenticate with the email server. After you create the refresh token, you can use it t
User task first?

2024-08-23 17:38 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +The wizard contains the following sections:
This feels like documenting the UI. Is there a way to change the headings to user tasks?

2024-08-23 17:41 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +The *OAuth Authentication* section enables you to create a set of tokens that don't rely on a user password to authenticate with the email server. After you create the refresh token, you can use it t
Suggest user-task heading: "Authenticate with OAuth"

2024-08-23 17:42 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/generate-oauth-token-steps.adoc
> +By using an activity parameter you don't need to upload a new version of your Workflow to RPA Manager if your token expires or your user gets logged out of your email provider. In this case, regenera
```suggestion
By using an activity parameter, you don't need to upload a new version of your Workflow to RPA Manager if your token expires or your user gets logged out of your email provider. In this case, regenerate the refresh token for the same user with the *OAuth Token Creator* and update the assigned activity parameter on RPA Manager.
```

2024-08-23 17:43 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-credentials-properties.adoc
> +Select this option to specify OAuth credentials created with the xref:toolbox-variable-handling-credentials-for-oauth.adoc[Credentials for OAuth] Action Step.
Do you need the hard-coded link text?

2024-08-23 17:43 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-credentials-properties.adoc
> +Select this option to specify custom OAuth credentials for this Action Step.
```suggestion
Specifies custom OAuth credentials for this Action Step
```

2024-08-23 17:44 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-credentials-properties.adoc
> +Select this option to specify custom OAuth credentials for this Action Step.
(Suggest applying to all descriptions)

2024-08-23 17:53 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-credentials-properties.adoc
> +To authenticate with the OAuth Host, an Azure application must be defined in your space. This Azure application has an ID, that is unique in the entire OAuth Host space and it allows users to explici
Is there a way to have a brief description of what this is first and then this as a separate paragraph? (For scannability and parallelism)

2024-08-23 17:54 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-credentials-properties.adoc
> +The URI to which the OAuth Host redirects after the user completes the authentication attempt. This redirect URI must be registered with the Azure application. If the entered redirect URI matches one
```suggestion
The URI that the OAuth Host redirects to after the user completes the authentication attempt. This redirect URI must be registered with the Azure application. If the entered redirect URI matches one of the registered URIs, the OAuth Host allows the authentication.
```

2024-08-23 17:55 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-credentials-properties.adoc
> +The URI to which the OAuth Host redirects after the user completes the authentication attempt. This redirect URI must be registered with the Azure application. If the entered redirect URI matches one
(Our style is to avoid that "to which" construction - less formal)

2024-08-23 18:12 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-credentials-properties.adoc
> +(*Required*) Enables access via a refresh token, which you can use to repeatedly log in to the email services without requiring user interaction each time.
Don't use bold for emphasis - bold text isn't translated.

2024-08-23 18:13 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-credentials-properties.adoc
> +Saves the current data for further use when <<generate-oauth-token, Generating an OAuth Refresh Token>>.
When using a link inline, use sentence capitalization.

2024-08-23 18:14 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +This step starts the authentication process with the OAuth Host, which opens the login page in your default browser.
```suggestion
This step starts the authentication process with the OAuth host, which opens the login page in your default browser. 
```

2024-08-23 18:15 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +This step starts the authentication process with the OAuth Host, which opens the login page in your default browser.
Is Host a proper noun? If not, then lc (globally) unless in the UI.

2024-08-23 18:17 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +Instead of authenticating via the *Mail Session (OAuth) wizard*, you can pin the refresh token if you obtain it externally. In this case, you still need to populate or pin the remaining fields.
Should "wizard" be bold here?

2024-08-23 18:20 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +Use the *Send test mail* button to check the connection to the SMTP server and send a test email to the email address specified in the *Sendtest mail to* field.
To check the connection to the SMTP server and send a test email to the email address specified in the *Sendtest mail to* field, click *Send test mail*.

2024-08-23 18:21 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +* xref:toolbox-mail-operations-read-mail.adoc[Read Mail]
hard-coded link text necessary?

2024-08-23 18:21 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +* https://azure.microsoft.com/en-us/[Azure^]
(No need to add the caret for http links now)

2024-08-23 18:22 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-variable-handling-credentials-for-oauth.adoc
> +== Generating an OAuth Refresh Token
```suggestion
== Generate an OAuth Refresh Token
```

2024-08-23 18:22 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-variable-handling-credentials-for-oauth.adoc
> +== Generating an OAuth Refresh Token
Imperative for tasks; gerund for collections of tasks

2024-08-23 18:23 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-mail-operations-mail-session-oauth.adoc
> +== Before you Begin
```suggestion
== Before You Begin
```

2024-08-27 13:34 UTC, merged