W-16161768 upload to google drive
mulesoft/docs-rpa pull request #413
Opened 2024-08-20 17:59 UTC by Cristian-Venticinque

2024-08-22 14:42 UTC, ahelmbold commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +You can export Google Docs, Sheets, and Slides into a selection of supported formats including PDF.
This sentence can be removed, think it is still from the Download from Google Drive

2024-08-22 14:44 UTC, ahelmbold commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +You can obtain the folder ID by navigating to said Google Drive folder and extracting the ID from the URL (the ID is the value `folder/`). If you don't specify a folder ID, this action step upload th
We should add here that users can also obtain the folder ID by using the Search in Google Drive action step and "Search for: Folders" there, they will get Folder IDs matching their search criteria.

2024-08-22 14:44 UTC, ahelmbold requested changes
See comments

2024-08-26 16:53 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-authentication-settings.adoc
> +
Consider a table for reference info.

2024-08-26 16:54 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-authentication-settings.adoc
> +Type of Google API credentials. For example, `service_account`.
```suggestion
Type of Google API credentials, for example, `service_account`
```

2024-08-26 16:54 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-authentication-settings.adoc
> +Type of Google API credentials. For example, `service_account`.
If you make this change, all descriptions are sentence fragments and don't need the period.

2024-08-26 16:55 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/_partials/oauth-authentication-settings.adoc
> +Type of Google API credentials. For example, `service_account`.
I think "type" and "credential" should both be either singular or plural.

2024-08-26 16:59 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +Upload files to your Google Drive.
s/d: summarize the topic and give user value.

2024-08-26 16:59 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +Before uploading a file, ensure you:
See previous suggestion to make these imperative/present tense.

2024-08-26 17:01 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +See xref:common-properties.adoc[Common Properties]
```suggestion
See xref:common-properties.adoc[Common Properties].
```

2024-08-26 17:02 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +You can specify either an absolute path or a relative to the Base Path.
```suggestion
You can specify an absolute path or a path relative to the Base Path. 
```

2024-08-26 17:02 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +* *File Operation Settings*
See prev suggestion about using a table.

2024-08-26 17:05 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +You can obtain the folder ID by using the Search in Google Drive action step and searching for the folder, or by navigating to said Google Drive folder and extracting the ID from the URL (the ID is t
```suggestion
To get the folder ID, use Search in the Google Drive action step to find the folder. You can also go to the Google Drive folder and extract the ID (the value `folder/`) from the URL. If you don't specify a folder ID, this action step uploads the file to the root folder. 
```

2024-08-26 17:06 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +* *Upload successful* (Boolean)
See previous comment on similar boolean variable. 

No terminating punctuation for sentence fragments.

2024-08-26 17:07 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +== Wizard
See prev comment about making this the task (imperative) and moving to the beginning of the file.

2024-08-26 17:08 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +Specify the *Directory path* and the *File name* of the file to upload. You can provide a *Google Drive Folder ID* to upload the file into this folder. If you don't provide this value, this action st
To avoid using UI elements as words in the sentence, lowercase and remove bold.

2024-08-26 17:12 UTC, hannanelson commented on rpa-builder/6.7/modules/ROOT/pages/toolbox-google-workspace-upload-to-google-drive.adoc
> +See xref:common-properties.adoc[Common Properties]
Hard-coded link text?

2024-08-26 19:21 UTC, merged