W 11853512 rpa rns cv
mulesoft/docs-rpa pull request #97
Opened 2022-11-24 17:48 UTC by Cristian-Venticinque

2022-11-25 09:17 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +* The new Credentials for OAuth Action Step enables you to configure OAuth credentials once and reuse them within other Action Steps.
I would emphasize here that the OAuth credentials can be generated with the help of this action step at workflow runtime, the "Once" bothers me here and something with "at runtime" is missing

2022-11-25 09:21 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +// This seems like a pre-release fix, do we need to include it? | |W-11887027 Send test mail with Exchange
No, entry can be deleted

2022-11-25 09:21 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +// This seems like a pre-release fix, do we need to include it?| |W-11918594 OutlookMailSession contains previous data
No, entry can be deleted

2022-11-25 09:22 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +// This seems like a pre-release fix, do we need to include it?| |W-11968720 Fixed Errorhandling None not working on various Control Blocks
No, entry can be deleted

2022-11-25 09:40 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +| The Message Box Action Step no longer fails to recognize a normalized JSON from an AWS Action Step as a pin variable.  |W-12065095
This can be removed bug was only in pre-release version.

2022-11-25 09:44 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +// This one can be shown in What's new as an update | |W-12041665 Removed Online Manual Selection in Settings Dialog
We might remove this entry completely.  Yes this was removed in the product but was already obsolete before and only a clean up.

2022-11-25 10:05 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +// This one can be shown in What's new as an update | |W-12041695 renamed "use all user folder" setting
Yes, move to What's new

2022-11-25 10:07 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +// | |W-11508834
Can be removed

2022-11-25 10:09 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +// | |W-12065550
For transparency reasons we should show this bug. Even the chance customers had face it is very small it still was somehow breaking bug which had no solution or error handling for users to solve it by themself.

2022-11-25 10:12 UTC, ahelmbold commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
Two new feature stories are missing:
- W-11747186 New activity parameter - OAuth credentials
- W-11657560 Mail OAuth - accessing refresh token

2022-11-25 10:17 UTC, ahelmbold requested changes
See my comments

2022-11-25 15:24 UTC, ahelmbold submitted a review, later dismissed
Looks good, can approve 👍

2022-11-28 15:25 UTC, JennyHajee commented on rpa-home/modules/ROOT/pages/release-notes/rpa-builder-6.1-release-notes.adoc
> +| The Message Box Action Step Wizard now validates that the Title and Text values are not empty. |W-11864908
```suggestion
| The Message Box Action Step Wizard now validates that the `Title` and `Text` values are not empty. |W-11864908
```

2022-11-28 15:30 UTC, JennyHajee submitted a review, later dismissed

2023-02-15 13:32 UTC, Cristian-Venticinque commented
Closing outdated PR. This update was addressed already.

2023-02-15 13:32 UTC, closed without merging